#!/usr/bin/env python3
"""dump_sifrei_yesod.py — generate idempotent SQL dump of sifrei_yesod tables.

Connects to the dev DB (`ETZ_CHAIM_DB_URL` or default), reads every row of the
8 `sifrei_yesod_*` tables in FK-safe order, and writes
`INSERT … ON CONFLICT DO UPDATE/NOTHING` statements to
`etzchaim/deploy/init-db/99-sifrei_yesod-data.sql`.

The output is consumed by `etzchaim update` via `_apply_migrations()` (cf.
etzchaim/cli/commands/update.py), so users automatically receive every newly
transposed perek the next time they run `etzchaim update`.

The ON CONFLICT clauses mirror sofer.py (`ensure_*` / `ingest_perek`) so the
dump is semantically identical to a fresh re-run of sofer.

FK to perakim.id is resolved at apply time via a sub-SELECT on
(sefer_id, heikhal_number, shaar_number, perek_number), so the SERIAL ids of
the dev DB do not leak into users' DBs.

Usage:
    python scripts/dump_sifrei_yesod.py
    python scripts/dump_sifrei_yesod.py --output /path/to/file.sql
    python scripts/dump_sifrei_yesod.py --db postgresql://user@host/db
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys
from pathlib import Path

import psycopg2
import psycopg2.extras

DB_URL = (
    os.environ.get("ETZ_CHAIM_DB_URL")
    or os.environ.get("ETZ_CHAIM_DB", "postgresql://localhost/etz_chaim")
)
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "etzchaim" / "deploy" / "init-db" / "99-sifrei_yesod-data.sql"


def _mog(cur, sql: str, params: tuple) -> str:
    """Build a single INSERT statement string from a parameterized template."""
    return cur.mogrify(sql, params).decode("utf-8") + ";\n"


def _header(counts: dict[str, int]) -> str:
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    summary = ", ".join(f"{v} {k}" for k, v in counts.items() if v > 0)
    return (
        "-- 99-sifrei_yesod-data.sql\n"
        "-- AUTO-GENERATED by scripts/dump_sifrei_yesod.py — DO NOT EDIT MANUALLY.\n"
        "-- Re-runs idempotently via ON CONFLICT DO UPDATE / DO NOTHING.\n"
        "-- Applied by etzchaim/cli/commands/update.py:_apply_migrations() so every\n"
        "-- `etzchaim update` ships the latest Sifrei Yesod corpus.\n"
        f"-- Generated at: {now}\n"
        f"-- Contents: {summary}\n"
        "\n"
        "BEGIN;\n"
    )


# ── Section emitters ─────────────────────────────────────────────


def _dump_sefarim(cur, out: list[str]) -> int:
    cur.execute("SELECT * FROM sifrei_yesod_sefarim ORDER BY sefer_id")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ sefarim ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_sefarim
        (sefer_id, titre_he, titre_fr, auteur, maitre, edition_base,
         date_composition, structure_type, nombre_shaarim, description)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (sefer_id) DO UPDATE SET
        titre_he = EXCLUDED.titre_he,
        titre_fr = EXCLUDED.titre_fr,
        auteur = EXCLUDED.auteur,
        maitre = EXCLUDED.maitre,
        edition_base = EXCLUDED.edition_base,
        date_composition = EXCLUDED.date_composition,
        structure_type = EXCLUDED.structure_type,
        nombre_shaarim = EXCLUDED.nombre_shaarim,
        description = EXCLUDED.description,
        updated_at = NOW()"""
    for row in rows:
        out.append(_mog(cur, sql, (
            row["sefer_id"], row["titre_he"], row["titre_fr"], row["auteur"],
            row["maitre"], row["edition_base"], row["date_composition"],
            row["structure_type"], row["nombre_shaarim"], row["description"],
        )))
    return len(rows)


def _dump_heikhalot(cur, out: list[str]) -> int:
    cur.execute("SELECT * FROM sifrei_yesod_heikhalot ORDER BY sefer_id, heikhal_number")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ heikhalot ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_heikhalot
        (sefer_id, heikhal_number, heikhal_name_he, heikhal_name_fr,
         nombre_shaarim, description)
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT (sefer_id, heikhal_number) DO UPDATE SET
        heikhal_name_he = EXCLUDED.heikhal_name_he,
        heikhal_name_fr = EXCLUDED.heikhal_name_fr,
        nombre_shaarim = EXCLUDED.nombre_shaarim,
        description = EXCLUDED.description,
        updated_at = NOW()"""
    for row in rows:
        out.append(_mog(cur, sql, (
            row["sefer_id"], row["heikhal_number"], row["heikhal_name_he"],
            row["heikhal_name_fr"], row["nombre_shaarim"], row["description"],
        )))
    return len(rows)


def _dump_shaarim(cur, out: list[str]) -> int:
    cur.execute(
        "SELECT * FROM sifrei_yesod_shaarim "
        "ORDER BY sefer_id, heikhal_number, shaar_number"
    )
    rows = cur.fetchall()
    out.append(f"\n-- ═══ shaarim ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_shaarim
        (sefer_id, heikhal_number, shaar_number, shaar_name_he, shaar_name_fr,
         nombre_perakim, sujet_principal, concepts_cles,
         connexions_modules, connexions_domaines)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (sefer_id, heikhal_number, shaar_number) DO UPDATE SET
        shaar_name_he = EXCLUDED.shaar_name_he,
        shaar_name_fr = EXCLUDED.shaar_name_fr,
        nombre_perakim = EXCLUDED.nombre_perakim,
        sujet_principal = EXCLUDED.sujet_principal,
        concepts_cles = EXCLUDED.concepts_cles,
        connexions_modules = EXCLUDED.connexions_modules,
        connexions_domaines = EXCLUDED.connexions_domaines,
        updated_at = NOW()"""
    for row in rows:
        out.append(_mog(cur, sql, (
            row["sefer_id"], row["heikhal_number"], row["shaar_number"],
            row["shaar_name_he"], row["shaar_name_fr"], row["nombre_perakim"],
            row["sujet_principal"], row["concepts_cles"],
            row["connexions_modules"], row["connexions_domaines"],
        )))
    return len(rows)


def _dump_perakim(cur, out: list[str]) -> tuple[int, dict[int, tuple]]:
    """Dump perakim and return mapping {dev_id: (sefer, heikhal, shaar, perek)}.

    The mapping is needed to translate `perek_id` foreign keys in the assertions/
    relations/principes inserts into a sub-SELECT against the user's DB at apply
    time (since SERIAL ids differ between dev and prod DBs).
    """
    cur.execute(
        "SELECT * FROM sifrei_yesod_perakim "
        "ORDER BY sefer_id, heikhal_number, shaar_number, perek_number"
    )
    rows = cur.fetchall()
    out.append(f"\n-- ═══ perakim ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_perakim
        (sefer_id, heikhal_number, shaar_number, perek_number,
         source_edition, transposed_by, version, strates, yaml_hash)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (sefer_id, heikhal_number, shaar_number, perek_number) DO UPDATE SET
        source_edition = EXCLUDED.source_edition,
        transposed_by = EXCLUDED.transposed_by,
        version = EXCLUDED.version,
        strates = EXCLUDED.strates,
        yaml_hash = EXCLUDED.yaml_hash,
        updated_at = NOW()"""
    perek_id_to_coords: dict[int, tuple] = {}
    for row in rows:
        perek_id_to_coords[row["id"]] = (
            row["sefer_id"], row["heikhal_number"],
            row["shaar_number"], row["perek_number"],
        )
        out.append(_mog(cur, sql, (
            row["sefer_id"], row["heikhal_number"], row["shaar_number"],
            row["perek_number"], row["source_edition"], row["transposed_by"],
            row["version"], row["strates"], row["yaml_hash"],
        )))
    return len(rows), perek_id_to_coords


def _dump_concepts(cur, out: list[str]) -> int:
    """Concepts: ON CONFLICT DO NOTHING (matches sofer.py:295-302)."""
    cur.execute("SELECT * FROM sifrei_yesod_concepts ORDER BY id")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ concepts ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_concepts
        (concept_id, nom_he, nom_fr, description, domaine,
         premiere_apparition, metadata)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (concept_id) DO NOTHING"""
    for row in rows:
        # metadata is JSONB → wrap in psycopg2.extras.Json so mogrify emits
        # a properly-quoted JSON literal.
        meta = psycopg2.extras.Json(row["metadata"]) if row["metadata"] is not None else None
        out.append(_mog(cur, sql, (
            row["concept_id"], row["nom_he"], row["nom_fr"], row["description"],
            row["domaine"], row["premiere_apparition"], meta,
        )))
    return len(rows)


# Sub-SELECT template used to resolve perek_id from logical coords.
# Returns NULL if the perek is missing — but FK NOT NULL on the table will
# raise, which is the desired behavior (perakim must be inserted first).
_PEREK_LOOKUP = (
    "(SELECT id FROM sifrei_yesod_perakim "
    "WHERE sefer_id = %s AND heikhal_number = %s "
    "AND shaar_number = %s AND perek_number = %s)"
)


def _dump_assertions(cur, out: list[str], coords_map: dict[int, tuple]) -> int:
    cur.execute("SELECT * FROM sifrei_yesod_assertions ORDER BY id")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ assertions ({len(rows)} rows) ═══\n")
    sql = f"""INSERT INTO sifrei_yesod_assertions
        (assertion_id, perek_id, source_he, source_ref, assertion,
         assertion_type, concepts, mapping_modules, mapping_tables,
         mapping_partzufim, mapping_relevance, strate)
    VALUES (%s, {_PEREK_LOOKUP}, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (assertion_id) DO UPDATE SET
        perek_id = EXCLUDED.perek_id,
        source_he = EXCLUDED.source_he,
        source_ref = EXCLUDED.source_ref,
        assertion = EXCLUDED.assertion,
        assertion_type = EXCLUDED.assertion_type,
        concepts = EXCLUDED.concepts,
        mapping_modules = EXCLUDED.mapping_modules,
        mapping_tables = EXCLUDED.mapping_tables,
        mapping_partzufim = EXCLUDED.mapping_partzufim,
        mapping_relevance = EXCLUDED.mapping_relevance,
        strate = EXCLUDED.strate,
        embedding = NULL,
        updated_at = NOW()"""
    for row in rows:
        coords = coords_map[row["perek_id"]]
        concepts = psycopg2.extras.Json(row["concepts"]) if row["concepts"] is not None else None
        out.append(_mog(cur, sql, (
            row["assertion_id"],
            *coords,
            row["source_he"], row["source_ref"], row["assertion"],
            row["assertion_type"], concepts,
            row["mapping_modules"], row["mapping_tables"],
            row["mapping_partzufim"], row["mapping_relevance"],
            row["strate"],
        )))
    return len(rows)


def _dump_relations(cur, out: list[str], coords_map: dict[int, tuple]) -> int:
    cur.execute("SELECT * FROM sifrei_yesod_relations ORDER BY id")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ relations ({len(rows)} rows) ═══\n")
    sql = f"""INSERT INTO sifrei_yesod_relations
        (relation_id, perek_id, relation_type, concept_from, concept_to,
         paire, via, nature, pattern, assertions_source,
         bidirectionnel, strate)
    VALUES (%s, {_PEREK_LOOKUP}, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (relation_id) DO UPDATE SET
        perek_id = EXCLUDED.perek_id,
        relation_type = EXCLUDED.relation_type,
        concept_from = EXCLUDED.concept_from,
        concept_to = EXCLUDED.concept_to,
        paire = EXCLUDED.paire,
        via = EXCLUDED.via,
        nature = EXCLUDED.nature,
        pattern = EXCLUDED.pattern,
        assertions_source = EXCLUDED.assertions_source,
        bidirectionnel = EXCLUDED.bidirectionnel,
        strate = EXCLUDED.strate,
        updated_at = NOW()"""
    for row in rows:
        coords = coords_map[row["perek_id"]]
        out.append(_mog(cur, sql, (
            row["relation_id"],
            *coords,
            row["relation_type"], row["concept_from"], row["concept_to"],
            row["paire"], row["via"], row["nature"], row["pattern"],
            row["assertions_source"], row["bidirectionnel"], row["strate"],
        )))
    return len(rows)


def _dump_principes(cur, out: list[str], coords_map: dict[int, tuple]) -> int:
    cur.execute("SELECT * FROM sifrei_yesod_principes ORDER BY id")
    rows = cur.fetchall()
    out.append(f"\n-- ═══ principes ({len(rows)} rows) ═══\n")
    sql = f"""INSERT INTO sifrei_yesod_principes
        (principe_id, perek_id, nom, source_assertions,
         formalisation, applications_ia, questions_ouvertes, strate, metadata)
    VALUES (%s, {_PEREK_LOOKUP}, %s, %s, %s, %s, %s, %s, %s)
    ON CONFLICT (principe_id) DO UPDATE SET
        perek_id = EXCLUDED.perek_id,
        nom = EXCLUDED.nom,
        source_assertions = EXCLUDED.source_assertions,
        formalisation = EXCLUDED.formalisation,
        applications_ia = EXCLUDED.applications_ia,
        questions_ouvertes = EXCLUDED.questions_ouvertes,
        strate = EXCLUDED.strate,
        metadata = EXCLUDED.metadata,
        embedding = NULL,
        updated_at = NOW()"""
    for row in rows:
        coords = coords_map[row["perek_id"]]
        meta = psycopg2.extras.Json(row["metadata"]) if row["metadata"] is not None else None
        out.append(_mog(cur, sql, (
            row["principe_id"],
            *coords,
            row["nom"], row["source_assertions"], row["formalisation"],
            row["applications_ia"], row["questions_ouvertes"], row["strate"],
            meta,
        )))
    return len(rows)


def _dump_cross_refs(cur, out: list[str]) -> int:
    """cross_refs has no UNIQUE constraint other than `id` (SERIAL).

    To keep the dump idempotent we WHERE NOT EXISTS the full natural key
    (source_assertion_id, target_assertion_id, target_sefer, target_ref,
    relation_type) — including target_assertion_id so duplicate auto-generated
    refs that point to different target_assertion_ids are preserved.
    target_assertion_id may be NULL, so we use IS NOT DISTINCT FROM.
    """
    cur.execute("SELECT * FROM sifrei_yesod_cross_refs ORDER BY id")
    rows = cur.fetchall()
    if not rows:
        return 0
    out.append(f"\n-- ═══ cross_refs ({len(rows)} rows) ═══\n")
    sql = """INSERT INTO sifrei_yesod_cross_refs
        (source_assertion_id, target_assertion_id, target_sefer,
         target_ref, relation_type, description)
    SELECT %s, %s, %s, %s, %s, %s
    WHERE NOT EXISTS (
        SELECT 1 FROM sifrei_yesod_cross_refs
        WHERE source_assertion_id = %s
          AND target_assertion_id IS NOT DISTINCT FROM %s
          AND target_sefer = %s
          AND target_ref = %s
          AND relation_type = %s
    )"""
    for row in rows:
        out.append(_mog(cur, sql, (
            row["source_assertion_id"], row["target_assertion_id"],
            row["target_sefer"], row["target_ref"],
            row["relation_type"], row["description"],
            # WHERE NOT EXISTS params
            row["source_assertion_id"], row["target_assertion_id"],
            row["target_sefer"], row["target_ref"], row["relation_type"],
        )))
    return len(rows)


# ── Entry point ──────────────────────────────────────────────────


def dump(db_url: str, output_path: Path) -> dict[str, int]:
    """Generate the SQL dump file. Returns row counts per table."""
    conn = psycopg2.connect(db_url)
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    out: list[str] = []
    out.append("__HEADER__\n")  # placeholder, replaced after we know counts

    counts: dict[str, int] = {}
    counts["sefarim"] = _dump_sefarim(cur, out)
    counts["heikhalot"] = _dump_heikhalot(cur, out)
    counts["shaarim"] = _dump_shaarim(cur, out)
    counts["perakim"], coords_map = _dump_perakim(cur, out)
    counts["concepts"] = _dump_concepts(cur, out)
    counts["assertions"] = _dump_assertions(cur, out, coords_map)
    counts["relations"] = _dump_relations(cur, out, coords_map)
    counts["principes"] = _dump_principes(cur, out, coords_map)
    counts["cross_refs"] = _dump_cross_refs(cur, out)

    out.append("\nCOMMIT;\n")
    out[0] = _header(counts)

    conn.close()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(out), encoding="utf-8")
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="dump_sifrei_yesod",
        description="Dump sifrei_yesod_* tables to an idempotent SQL file.",
    )
    parser.add_argument("--db", default=DB_URL, help="PostgreSQL URL")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output SQL path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    print(f"Reading from: {args.db}")
    print(f"Writing to:   {args.output}")
    try:
        counts = dump(args.db, args.output)
    except psycopg2.Error as exc:
        print(f"  ✗ PostgreSQL error: {exc}", file=sys.stderr)
        sys.exit(1)

    size_kb = args.output.stat().st_size / 1024
    print(f"\n  ✓ {size_kb:.1f} KB written")
    for table, n in counts.items():
        print(f"    {table:14s} {n:>6d}")


if __name__ == "__main__":
    main()
